#  wget -r --no-parent -A 'epel-release-*.rpm' http://dl.fedoraproject.org/pub/epel/7/x86_64/e/
#  rpm -Uvh dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-*.rpm
#  ls -l /etc/yum.repos.d/
#  systemctl start redis.service
#  systemctl status redis.service
#  redis-cli ping

---
- name: Redis | Install redis
  yum: name=redis-server
  tags: redis
